# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'ipaddr'
load './config.rb'
image = "centos/7"

def nodeIP(ips, id)
  return ((IPAddr.new ips)|(2+id)).to_s()
end

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", owner: "vagrant", group: "vagrant", rsync__auto: true, type: "virtualbox"

    (0..$worker_count).each do |index|
        node_name = (index == 0) ? "k8s-master" : "k8s-worker%d" % index

        config.vm.define node_name do |node|
            node.vm.box = image
            node.vm.hostname = node_name
			node.vm.network :private_network, ip: nodeIP($cluster_ips, index)
			node.vm.network :private_network, ip: nodeIP($manage_ips, index)
			node.vm.network :private_network, ip: nodeIP($private_ips, index)

            node.vm.provider :virtualbox do |vb|
                vb.name = node_name
				vb.cpus = (index == 0) ? 3 : 2
                vb.memory = (index == 0) ? $master_memory : $worker_memory
                vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            end

            node.vm.provision "shell", 
                name: "Base Installation (scripts/base.sh)",
                path: "scripts/base.sh"

        end
    end
end
